name: Deploy Github Page

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
      - run: git config --local user.email "action@github.com"
      - run: git config --local user.name "GitHub Action"
      - run: npm i
      - run: npm run build
      - run: git subtree push --prefix build https://${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}/${{secrets.REPO}}.git gh-pages