name: GitHub Actions Demo
on: [push]
jobs:
  Deploy-GitHub-Page:
    runs-on: main
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: npm run deploy
